spring:
  profiles:
    active:
    - dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql:///opms?useSSL=false
    username: root
    password: 123456
  redis:
    database: 0
    host: 127.0.0.1
    password: 123456
    port: 6379

mybatis:
  configuration:
    cache-enabled: true
    caches: com.cavelling.cache.RedisCache
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations:
  - com/cavelling/mapper/*.xml
  type-aliases-package: com.cavelling.model
      
    